// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.likaistentemppujenosasto.octo.domain;

import com.likaistentemppujenosasto.octo.domain.OctoUser;
import com.likaistentemppujenosasto.octo.domain.OctoUserDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect OctoUserDataOnDemand_Roo_DataOnDemand {
    
    declare @type: OctoUserDataOnDemand: @Component;
    
    private Random OctoUserDataOnDemand.rnd = new SecureRandom();
    
    private List<OctoUser> OctoUserDataOnDemand.data;
    
    public OctoUser OctoUserDataOnDemand.getNewTransientOctoUser(int index) {
        OctoUser obj = new OctoUser();
        setUsername(obj, index);
        return obj;
    }
    
    public void OctoUserDataOnDemand.setUsername(OctoUser obj, int index) {
        String username = "username_" + index;
        obj.setUsername(username);
    }
    
    public OctoUser OctoUserDataOnDemand.getSpecificOctoUser(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        OctoUser obj = data.get(index);
        Long id = obj.getId();
        return OctoUser.findOctoUser(id);
    }
    
    public OctoUser OctoUserDataOnDemand.getRandomOctoUser() {
        init();
        OctoUser obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return OctoUser.findOctoUser(id);
    }
    
    public boolean OctoUserDataOnDemand.modifyOctoUser(OctoUser obj) {
        return false;
    }
    
    public void OctoUserDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = OctoUser.findOctoUserEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'OctoUser' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<OctoUser>();
        for (int i = 0; i < 10; i++) {
            OctoUser obj = getNewTransientOctoUser(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
