// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.likaistentemppujenosasto.octo.domain;

import com.likaistentemppujenosasto.octo.domain.OctoUser;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect OctoUser_Roo_Configurable {
    
    declare @type: OctoUser: @Configurable;
    
}
